# The URL the site will be built for
base_url = "https://laio.sh"

title = 'laio'
description = 'Flexbox-inspired layout and session manager for tmux'

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

theme = "adidoks"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Syntax highlighting configuration
[markdown.highlighting]
theme = "github-dark"

[extra]
author = "Christian Kemper"
github = "https://github.com/ck3mp3r"
email = "christian.kemper@pm.me"
is_netlify = false

# SEO and meta
title_separator = "|"
title_addition = "Flexbox-inspired layout and session manager for tmux"

[extra.footer]
info = ' '

[[extra.menu.social]]
name = "Mastodon"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-mastodon" viewBox="0 0 16 16"><path d="M11.19 12.195c2.016-.24 3.77-1.475 3.99-2.603.348-1.778.32-4.339.32-4.339 0-3.47-2.286-4.488-2.286-4.488C12.062.238 10.083.017 8.027 0h-.05C5.92.017 3.942.238 2.79.765c0 0-2.285 1.017-2.285 4.488l-.002.662c-.004.64-.007 1.35.011 2.091.083 3.394.626 6.74 3.78 7.57 1.454.383 2.703.463 3.709.408 1.823-.1 2.847-.647 2.847-.647l-.06-1.317s-1.303.41-2.767.36c-1.45-.05-2.98-.156-3.215-1.928a3.614 3.614 0 0 1-.033-.496s1.424.346 3.228.428c1.103.05 2.137-.064 3.188-.189zm1.613-2.47H11.13v-4.08c0-.859-.364-1.295-1.091-1.295-.804 0-1.207.517-1.207 1.541v2.233H7.168V5.89c0-1.024-.403-1.541-1.207-1.541-.727 0-1.091.436-1.091 1.296v4.079H3.197V5.522c0-.859.22-1.541.66-2.046.456-.505 1.052-.764 1.793-.764.856 0 1.504.328 1.933.983L8 4.39l.417-.695c.429-.655 1.077-.983 1.934-.983.74 0 1.336.259 1.791.764.442.505.661 1.187.661 2.046v4.203z"/></svg>'
url = "https://toot.io/@ckemper"
weight = 10

[[extra.menu.social]]
name = "Blusky"
pre = '<svg width="22" height="22" id="Layer_2" data-name="Layer 2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 362.18 319.92"><defs><style>.cls-1 { fill: #0085ff; stroke-width: 0px; }</style></defs><g id="Layer_1-2" data-name="Layer 1"><path class="cls-1" d="M78.51,21.53c41.52,31.28,86.19,94.69,102.58,128.71v89.88c0-1.91-.74.25-2.32,4.91-8.56,25.22-41.98,123.63-118.4,44.96-40.24-41.42-21.61-82.85,51.64-95.35-41.9,7.15-89.02-4.67-101.94-51.02C6.34,130.28,0,48.16,0,37.07,0-18.49,48.55-1.03,78.51,21.53ZM283.67,21.53c-41.52,31.28-86.19,94.69-102.58,128.71v89.88c0-1.91.74.25,2.32,4.91,8.56,25.22,41.98,123.63,118.4,44.96,40.24-41.42,21.61-82.85-51.64-95.35,41.9,7.15,89.02-4.67,101.94-51.02,3.72-13.33,10.06-95.46,10.06-106.55,0-55.56-48.54-38.1-78.51-15.53Z"/></g></svg>'
url = "https://bsky.app/profile/kemper.buzz"
weight = 10

[[extra.menu.social]]
name = "GitHub"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>'
url = "https://github.com/ck3mp3r/laio-cli"
post = "v0.1.0"
weight = 20

