---
name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0,10,20,30,40,50 4 * * 2'
jobs:
  nix-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} 

      - name: Set up Git
        if: ${{ ! env.ACT }}
        run: |
          git config --global user.name "Christian Kemper"
          git config --global user.email "christian.kemper@me.com"

      - name: Run Renovate
        uses: renovatebot/github-action@v40.2.3
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/workflows/renovate.json
        env:
          LOG_LEVEL: debug
